name: Docs Test

on:
  workflow_dispatch:

env:
  PRIMARY_MAVEN_MODULE: ${{ github.event.repository.name }}

jobs:
  publish-pages:
    name: Publish dependencies and licenses to github pages
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
    - uses: actions/checkout@v4
      
    - name: Init Git and pull
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull

    - name: Setup - Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build site
      run: mvn -B site
      working-directory: ${{ env.PRIMARY_MAVEN_MODULE }}

    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./${{ env.PRIMARY_MAVEN_MODULE }}/target/site
